# Generated by Django 6.0 on 2025-12-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_answer_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentexam",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="answer",
            name="awarded_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.question"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exams.questionoption",
            ),
        ),
    ]
