# Generated by Django 6.0 on 2025-12-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_remove_studentexam_is_completed_answer_awarded_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="grading_policy",
            field=models.CharField(
                choices=[
                    ("no_negative", "بدون نمره منفی"),
                    ("negative_3", "نمره منفی (۳ غلط = ۱ صحیح)"),
                    ("negative_5", "نمره منفی (۵ غلط = ۱ صحیح)"),
                ],
                default="no_negative",
                help_text="سیاست محاسبه درصد",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, help_text="توضیحات بیشتر"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(help_text="عنوان آزمون", max_length=255),
        ),
    ]
