# Generated by Django 6.0 on 2025-12-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_exam_grading_policy_alter_exam_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentexam",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
