# Generated by Django 6.0 on 2026-01-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_studentexam_graded_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order"],
                "verbose_name": "سوال",
                "verbose_name_plural": "سوالات",
            },
        ),
    ]
