# Generated by Django 6.0 on 2026-01-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_students_classgroup_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
